cmdb/urls.py
#-*- coding: utf-8 -*-
'''
    Author: smallmi
    Blog: http://www.smallmi.com
'''

"""skyoms URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from cmdb import views, api

urlpatterns = [

    url(r'^server_list/$', views.server_list, name='server_list'),
    url(r'^server_add_page/$', views.server_add_page, name='server_add_page'),
    url(r'^server_add/$', views.server_add, name='server_add'),
    url(r'^server_edit_page/(?P<id>\d+)/$', views.server_edit_page, name='server_edit_page'),
    # url(r'^server_edit/$', views.server_edit, name='server_edit'),
    url(r'^server_edit/$', views.server_edit, name='server_edit'),
    # url(r'^server_detail/(?P<id>\d+)/$', views.server_detail, name='server_detail'),
    url(r'^server_delete/$', views.server_delete, name='server_delete'),
    url(r'^server_webssh/$', views.server_webssh, name='server_webssh'),

    url(r'^search$', api.server_search, name='server_search'),


    url(r'^server_group/$', views.server_group, name='server_group'),
    url(r'^group_add/$', views.group_add, name='group_add'),
    url(r'^group_edit/$', views.group_edit, name='group_edit'),
    url(r'^group_delete/$', views.group_delete, name='group_delete'),
    url(r'^group_search$', api.group_search, name='group_search'),



    url(r'^server_idc/$', views.server_idc, name='server_idc'),
    url(r'^idc_add/$', views.idc_add, name='idc_add'),
    url(r'^idc_edit/$', views.idc_edit, name='idc_edit'),
    url(r'^idc_delete/$', views.idc_delete, name='idc_delete'),
    url(r'^idc_search$', api.idc_search, name='idc_search'),

    url(r'^system_user/$', views.system_user, name='system_user'),
    url(r'^system_user_add/$', views.system_user_add, name='system_user_add'),
    url(r'^system_user_edit/$', views.system_user_edit, name='system_user_edit'),
    url(r'^system_user_delete/$', views.system_user_delete, name='system_user_delete'),
    url(r'^system_user_search$', api.system_user_search, name='system_user_search'),

    url(r'^group_server_detail/(?P<id>\d+)$', views.group_server_detail, name='group_server_detail'),
    url(r'^idc_server_detail/(?P<id>\d+)$', views.idc_server_detail, name='idc_server_detail'),
    url(r'^group_server_search$', api.group_server_search, name='group_server_search'),
    url(r'^idc_server_search$', api.idc_server_search, name='idc_server_search'),


    url(r'^postmachineinfo/$', views.postmachineinfo, name='postmachineinfo'),
    url(r'^flushAllHosts/$', views.flushAllHosts, name='flushAllHosts'),

]

omms/urls.py
#-*- coding: utf-8 -*-
'''
    Author: smallmi
    Blog: http://www.smallmi.com
'''
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from dashboard import views as dashboard_views


urlpatterns = [
    url(r'^$',dashboard_views.index, name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'accounts/', include('accounts.urls')),
    url(r'release/', include('release.urls')),
    url(r'cmdb/', include('cmdb.urls')),
    url(r'tasks/', include('tasks.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'monitor/', include('monitor.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

release/urls.py
#-*- coding: utf-8 -*-
'''
    Author: smallmi
    Blog: http://www.smallmi.com
'''

"""skyoms URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from release import views, api

urlpatterns = [

    url(r'^app_list/$', views.app_list, name='app_list'),
    # url(r'^server_add_page/$', views.server_add_page, name='server_add_page'),
    url(r'^app_add/$', views.app_add, name='app_add'),
    # url(r'^server_edit_page/(?P<id>\d+)/$', views.server_edit_page, name='server_edit_page'),
    # # url(r'^server_edit/$', views.server_edit, name='server_edit'),
    url(r'^app_edit/$', views.app_edit, name='app_edit'),
    # # url(r'^server_detail/(?P<id>\d+)/$', views.server_detail, name='server_detail'),
    url(r'^app_delete/$', views.app_delete, name='app_delete'),
    url(r'^search$', api.app_search, name='app_search'),
    #
    #
    # url(r'^server_group/$', views.server_group, name='server_group'),
    # url(r'^group_add/$', views.group_add, name='group_add'),
    # url(r'^group_edit/$', views.group_edit, name='group_edit'),
    # url(r'^group_delete/$', views.group_delete, name='group_delete'),
    # url(r'^group_search$', api.group_search, name='group_search'),
    #
    #
    #
    url(r'^app_platform/$', views.app_platform, name='app_platform'),
    url(r'^platform_add/$', views.platform_add, name='platform_add'),
    url(r'^platform_edit/$', views.platform_edit, name='platform_edit'),
    url(r'^platform_delete/$', views.platform_delete, name='platform_delete'),
    url(r'^platform_search$', api.platform_search, name='platform_search'),
    #
    url(r'^app_server_detail/(?P<id>\d+)$', views.app_server_detail, name='app_server_detail'),
    url(r'^platform_app_detail/(?P<id>\d+)$', views.platform_app_detail, name='platform_app_detail'),
    url(r'^app_server_search$', api.app_server_search, name='app_server_search'),
    url(r'^platform_app_search$', api.platform_app_search, name='platform_app_search'),
    #
    #
    url(r'^release_plan/$', views.release_plan, name='release_plan'),
    url(r'^release_add/$', views.release_add, name='release_add'),


    url(r'^release_history/$', views.release_history, name='release_history'),
    # url(r'^postmachineinfo/$', views.postmachineinfo, name='postmachineinfo'),

]

release/models.py
#-*- coding: utf-8 -*-
'''
    Author: smallmi
    Blog: http://www.smallmi.com
'''

from __future__ import unicode_literals

from django.db import models
from accounts.models import User


# Create your models here.


class Platform(models.Model):
    # 平台信息
    name = models.CharField(max_length=64, unique=True, verbose_name=u'平台名')
    owner = models.CharField(max_length=64, null=True, verbose_name=u'负责人')
    phone = models.CharField(max_length=64, null=True, verbose_name=u'手机号')
    created_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, verbose_name=u'创建者')
    date_created = models.DateTimeField(auto_now_add=True, null=True, verbose_name=u'创建时间')
    comment = models.TextField(blank=True, verbose_name=u'描述')

    def __unicode__(self):
        return self.name

    __str__ = __unicode__

    class Meta:
        permissions = (
            ("view_platform", ("查看平台")),
            ("add_platform", ("添加平台")),
            ("change_platform", ("编辑平台")),
            ("delete_platform", ("删除平台")),
        )
        default_permissions = ()


class AppProject(models.Model):
    # 应用信息
    java_version = (
        (1, u"version 1.6"),
        (2, u"version 1.7"),
        (3, u"version 1.8"),
    )

    app_name_en = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'英文名称')
    app_name_cn = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'中文名称')
    app_type = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'应用类型')
    platform = models.ForeignKey(Platform, blank=True, null=True, related_name='servers', on_delete=models.SET_NULL,
                                 verbose_name=u'所属平台')

    git_url = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'Git 地址')
    # git_branch = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'Git分支')
    git_properties = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'配置文件')
    java_version = models.IntegerField(choices=java_version, null=True, verbose_name=u'Java版本')

    ctime = models.DateTimeField(auto_now_add=True, verbose_name=u'创建时间')
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, verbose_name=u'创建者')
    comment = models.TextField(null=True, blank=True, verbose_name=u'描述')

    def __unicode__(self):
        return '%s（%s）' % (self.app_name_cn, self.app_name_en)

    __str__ = __unicode__

    class Meta:
        permissions = (
            ("view_appProject", ("查看应用信息")),
            ("add_appProject", ("添加应用")),
            ("change_appProject", ("编辑应用")),
            ("delete_appProject", ("删除应用")),
        )
        default_permissions = ()


class ReleasePlan(models.Model):
    # 发布计划
    app = models.ForeignKey(AppProject, blank=True, null=True, related_name='apps', on_delete=models.SET_NULL,
                            verbose_name=u'发布应用')
    git_branch = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'代码版本')
    app_version = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'应用版本')

    plan_status = models.NullBooleanField(default=False, null=True, blank=True, verbose_name=u'发布状态')

    ctime = models.DateTimeField(auto_now_add=True, verbose_name=u'创建时间')
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, verbose_name=u'创建者')
    comment = models.TextField(null=True, blank=True, verbose_name=u'描述')

    def __unicode__(self):
        return '%s - %s' % (self.git_branch, self.app_version)

    class Meta:
        permissions = (
            ("view_releasePlan", ("查看发布计划")),
            ("add_releasePlan", ("添加发布计划")),
            ("change_releasePlan", ("编辑发布计划")),
            ("delete_releasePlan", ("删除发布计划")),
        )
        default_permissions = ()

release/forms.py
#-*- coding: utf-8 -*-
'''
    Author: smallmi
    Blog: http://www.smallmi.com
'''

from django import forms
from release.models import AppProject, ReleasePlan


class AppProjectForm(forms.ModelForm):

    class Meta:
        model = AppProject
        exclude = ('author',)

        widgets = {
            'app_name_cn': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '输入应用中文名称，如：运营系统'}),
            'app_name_en': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '输入应用英文名称，如：manager'}),
            'app_type': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '输入应用类型，如：web，DB，中间件'}),
            'platform': forms.Select(attrs={'class': 'form-control'}),
            'java_version': forms.Select(attrs={'class': 'form-control'}),
            'git_url': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '输入Git完整地址'}),
            'git_properties': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '输入配置文件信息'}),
        }


class ReleasePlanForm(forms.ModelForm):

    class Meta:
        model = ReleasePlan
        exclude = ('author',)

        widgets = {
            'app': forms.Select(attrs={'class': 'form-control'}),
            'git_branch': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '输入封板ID或分支，如：master'}),
            'app_version': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '输入应用tag版本，如：V1.0.0'}),
            'comment': forms.Textarea(attrs={'class': 'form-control', 'placeholder': '输入应用此次上线升级内容'}),
        }

templates/release/app_modal.html
<!-- 新增服务器模态框（Modal） -->
<div class="modal inmodal" id="addInfoModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated fadeIn">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h3 class="control-label col-sm-3 col-lg-3" id="addModalLabel">
                    新增应用信息
                </h3>
                {#                        <label for="add_ProjectName" class="control-label col-sm-3 col-lg-3">新增主机</label>#}
            </div>
            <form class="form-horizontal" id="jquery_post_from" method="post" action={% url 'app_add' %}>
                <div class="modal-body" style="margin-top: 15px">
                    <input type="hidden" name="csrfmiddlewaretoken"
                           value="kRaVIjNCyIT8a9V7EzT7ffeSH3avSyg7">
                    <div class="form-group">
                        <label class="col-sm-3 col-lg-3 control-label">{{ form.app_name_cn.label }}</label>
                        <div class="col-sm-8 col-lg-8">{{ form.app_name_cn }}</div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-3 col-lg-3 control-label">{{ form.app_name_en.label }}</label>
                        <div class="col-sm-8 col-lg-8">{{ form.app_name_en }}</div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-3 col-lg-3 control-label">{{ form.app_type.label }}</label>
                        <div class="col-sm-8 col-lg-8">{{ form.app_type }}
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-3 col-lg-3 control-label">{{ form.git_url.label }}</label>
                        <div class="col-sm-8 col-lg-8">{{ form.git_url }}</div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-3 col-lg-3 control-label">{{ form.git_properties.label }}</label>
                        <div class="col-sm-8 col-lg-8">{{ form.git_properties }}</div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-3 col-lg-3 control-label">{{ form.java_version.label }}</label>
                        <div class="col-sm-8 col-lg-8">{{ form.java_version }}</div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-3 col-lg-3 control-label">{{ form.platform.label }}</label>
                        <div class="col-sm-8 col-lg-8">{{ form.platform }}</div>
                    </div>


                    <div style="text-align:center">
                        <button id="reset" class="btn btn-white" type="cancel"> 重置</button>
                        <button type="submit" class="btn btn-primary"> 提交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


<!-- 编辑服务器模态框（Modal） -->
    <div class="modal inmodal" id="editInfoModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content animated fadeIn">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h3 class="control-label col-sm-3 col-lg-3" id="editModalLabel">
                        编辑应用信息
                    </h3>
                </div>
                <div class="modal-body" style="margin-top: 15px">
                    <form class="form-horizontal" id="jquery_post_from" method="post" action="">
                        <input type="hidden" name="csrfmiddlewaretoken"
                               value="kRaVIjNCyIT8a9V7EzT7ffeSH3avSyg7">
                        <div class="hidden">
                            <label for="edit_Id" class="control-label col-sm-3 col-lg-3">应用Id</label>
                            <div class="col-sm-8 col-lg-8">
                                <input type="text" class="form-control" id="app_id" name="app_id" value={{ i.id }}>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-lg-3 control-label">{{ form.app_name_cn.label }}</label>
                            <div class="col-sm-8 col-lg-8">
                                <input class="form-control" id="app_name_cn" name="app_name_cn" maxlength="100" type="text" value={{ i.app_name_cn }}>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-lg-3 control-label">{{ form.app_name_en.label }}</label>
                            <div class="col-sm-8 col-lg-8">
                                <input class="form-control" id="app_name_en" name="app_name_en" maxlength="100" type="text" value={{ i.app_name_en }}>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-lg-3 control-label">{{ form.app_type.label }}</label>
                            <div class="col-sm-8 col-lg-8">
                                <input class="form-control" id="app_type" name="app_type" maxlength="100" type="text" value={{ i.app_type }}>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-lg-3 control-label">{{ form.git_url.label }}</label>
                            <div class="col-sm-8 col-lg-8">
                                <input class="form-control" id="git_url" name="git_url" maxlength="100" type="text" value={{ i.git_url }}>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-lg-3 control-label">{{ form.git_properties.label }}</label>
                            <div class="col-sm-8 col-lg-8">
                                <input class="form-control" id="git_properties" name="git_properties" maxlength="100" type="text"
                                       value={{ i.git_properties }}>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-lg-3 control-label">{{ form.java_version.label }}</label>
                            <div class="col-sm-8 col-lg-8">
                                <select id="edit_java_version" name="edit_java_version" class="form-control">
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 col-lg-3 control-label">{{ form.platform.label }}</label>
                            <div class="col-sm-8 col-lg-8">
                                <select id="edit_platform" name="edit_platform" class="form-control">
                                </select>
                            </div>
                        </div>
                    </form>
                    <div style="text-align:center">
                        <button id="reset" class="btn btn-white" type="cancel"> 重置</button>
                        <button id="editSave" class="btn btn-primary"> 提交</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

templates/release/app_table.html
{% for i in content %}
    <tr class="gradeA odd" role="row">
        <td class="sorting_1">{{ forloop.counter }}</td>
        <td class="center"><a href="/release/app_server_detail/{{ i.id }}">{{ i.app_name_cn}}（{{ i.app_name_en }}）</a></td>
        <td class="center">{{ i.average_server }}</td>
        <td class="center">{{ i.app_type }}</td>
        <td class="center">{{ i.platform }}</td>
        <td class="center">{{ i.java_version }}</td>
        {% if i.java_version != 0 %}
            <td class="center">{{ i.get_java_version_display }}</td>
        {% else %}
            <td class="center">未使用</td>
        {% endif %}
        <td class="center">{{ i.author.fullname }}</td>
        <td class="center">{{ i.ctime }}</td>

        <td class="center">
            <button data-row="{{ i.id }}|{{ i.app_name_cn }}|{{ i.app_name_en }}|{{ i.app_type }}|{{ i.git_url }}|{{ i.git_properties }}|{{ i.platform_id }}|{{ i.java_version }}" class="btn btn-xs btn-warning btn-edit" data-toggle="modal" data-target="#editInfoModal">变更</button>
            <a class="btn btn-xs btn-danger" id="app_delete_{{i.id}}">删除</a>
        </td>
    </tr>


    <script type="text/javascript">
        /**
         * 编辑表单
         * **/

        $('.btn-edit').on('click', function (event) {
            var platforms ={{ platforms | safe}};
            var java_version_list = {{ java_version_list | safe}};

            var btn = $(event.target);
            var row = btn.data('row').split('|');

            $('#app_id').val(row[0]);
            $('#app_name_cn').val(row[1]);
            $('#app_name_en').val(row[2]);
            $('#app_type').val(row[3]);
            $('#git_url').val(row[4]);
            $('#git_properties').val(row[5]);

            $('#edit_platform').empty();
            $('#edit_java_version').empty();

            var platform = row[6]
            var java_version = row[7];

            jQuery.each(java_version_list,function (key, value) {
                var t = jQuery("<option value=" + value[0]+">" + value[1] + "</option>");
               if(value[0] == java_version){
                    t.attr("selected","selected");
               }
                $('#edit_java_version').append(t);
            });

            $('#edit_platform').append("<option value=''>----------</option>");
            jQuery.each(platforms, function (key, value) {
                var t = jQuery("<option value=" + value[0] + ">" + value[1] + "</option>");
                if (value[0] == platform) {
                    t.attr("selected", "selected");
                }
                $('#edit_platform').append(t);
            });


            row_group = row[5].split(',');
            if (groups != "") {
                $.each(groups, function (key, value) {
                    var obj = document.getElementById("edit_groups");
                    var op = new Option(value[1], value[0])
                    if (row_group.contains(value[1])) {
                        op.selected = true;
                    }
                    obj.add(op);
                });
            } else if (groups == "") {

                $.each(groups, function (key, value) {
                    var obj = document.getElementById("edit_groups");
                    var op = new Option(value[1], value[0])
                    obj.add(op);
                });
            }
            resetChosen();
        })
    </script>


    <script>
        /*
        *删除机器信息
        */
        $("table tbody tr td a[id^='app_delete']").click(function () {
            var id_val = $(this).attr('id');
            var id = id_val.split('_')[2];
            var data = {"id": id};
            data = JSON.stringify(data);
            var url = "/release/app_delete/";

            var index = layer.confirm('确定删除吗？', {
                btn: ['确定', '取消'] //按钮
            }, function () {
                $.post(url, {data: data}, function (msg) {
                    ajax_callback(msg);
                });
            }, function () {
                layer.close(index)
            });
        });


        /*
        *保存编辑服务器信息数据
        */
        $('#editSave').click(function () {
            var app_id = $("#app_id").val();
            var app_name_cn = $("#app_name_cn").val();
            var app_name_en = $("#app_name_en").val();
            var app_type = $("#app_type").val();
            var git_url = $("#git_url").val();
            var git_properties = $("#git_properties").val();
            var edit_java_version = $("#edit_java_version").find("option:selected").val();
            var edit_platform = $("#edit_platform").find("option:selected").val();
            data = {
                "app_id": app_id,
                "app_name_cn": app_name_cn,
                "app_name_en": app_name_en,
                "app_type": app_type,
                "git_url": git_url,
                "git_properties": git_properties,
                "edit_java_version": edit_java_version,
                "edit_platform": edit_platform
            };
            data = JSON.stringify(data);
            var url = "/release/app_edit/";

            $.post(url, {data: data}, function (msg) {
                $('#editInfoModal').modal('hide')
                ajax_callback(msg);
            });
        });

        /*
        *ajax get callback
        */
        function ajax_callback(msg) {
            var msg = $.parseJSON(msg);
            var index = layer.alert(msg, { //layer控件提示信息
                skin: 'layui-layer-molv' //样式类名
            }, function () {
                if (msg == '成功') {
                    window.location = "/release/app_list/";
                }
                else if (msg == '失败') {
                    window.location = "/release/app_list/";
                }
                    {#        else if (msg == '无权限操作'){#}
                    {#            window.location="/cmdb/server_list/";#}
                    {#        }#}
                else {
                    layer.close(index)
                }
            });
        }

    </script>
{% endfor %}

templates/release/platform_app_table.html
{% load accounts_tag %}
{% for i in content %}
    <tr class="gradeA odd" role="row">
        <td class="sorting_1">{{ forloop.counter }}</td>
        <td class="center">{{ i.app_name_cn}}（{{ i.app_name_en }}）</td>
        <td class="center">{{ i.app_type }}</td>
        <td class="center">{{ i.java_version }}</td>
        {% if i.java_version != 0 %}
            <td class="center">{{ i.get_java_version_display }}</td>
        {% else %}
            <td class="center">未使用</td>
        {% endif %}
        <td class="center">{{ i.ctime }}</td>

        <td class="center">
            <button data-row="{{ i.id }}|{{ i.app_name_cn }}|{{ i.app_name_en }}|{{ i.app_type }}|{{ i.git_url }}|{{ i.git_properties }}|{{ i.platform_id }}|{{ i.java_version }}" class="btn btn-xs btn-warning btn-edit" data-toggle="modal" data-target="#editInfoModal">变更</button>
            <a class="btn btn-xs btn-danger" id="app_delete_{{i.id}}">删除</a>
        </td>
    </tr>


    <script type="text/javascript">

        /**
         * 编辑表单
         * **/

        $('.btn-edit').on('click', function (event) {

            var platforms ={{ platforms | safe}};
            var java_version_list = {{ java_version_list | safe}};

            var btn = $(event.target);
            var row = btn.data('row').split('|');

            $('#app_id').val(row[0]);
            $('#app_name_cn').val(row[1]);
            $('#app_name_en').val(row[2]);
            $('#app_type').val(row[3]);
            $('#git_url').val(row[4]);
            $('#git_properties').val(row[5]);

            $('#edit_platform').empty();
            $('#edit_java_version').empty();

            var platform = row[6]
            var java_version = row[7];

            jQuery.each(java_version_list,function (key, value) {
                var t = jQuery("<option value=" + value[0]+">" + value[1] + "</option>");
               if(value[0] == java_version){
                    t.attr("selected","selected");
               }
                $('#edit_java_version').append(t);
            });

            $('#edit_platform').append("<option value=''>----------</option>");
            jQuery.each(platforms, function (key, value) {
                var t = jQuery("<option value=" + value[0] + ">" + value[1] + "</option>");
                if (value[0] == platform) {
                    t.attr("selected", "selected");
                }
                $('#edit_platform').append(t);
            });

        })
    </script>

    <script>
        /*
        *删除机器信息
        */
        $("table tbody tr td a[id^='app_delete']").click(function () {
            var id_val = $(this).attr('id');
            var id = id_val.split('_')[2];
            var data = {"id": id};
            data = JSON.stringify(data);
            var url = "/release/app_delete/";

            var index = layer.confirm('确定删除吗？', {
                btn: ['确定', '取消'] //按钮
            }, function () {
                $.post(url, {data: data}, function (msg) {
                    update_ajax_callback(msg, {{ platformId }});
                });
            }, function () {
                layer.close(index)
            });
        });


         /*
        *保存编辑服务器信息数据
        */
        $('#editSave').click(function () {
            var app_id = $("#app_id").val();
            var app_name_cn = $("#app_name_cn").val();
            var app_name_en = $("#app_name_en").val();
            var app_type = $("#app_type").val();
            var git_url = $("#git_url").val();
            var git_properties = $("#git_properties").val();
            var edit_java_version = $("#edit_java_version").find("option:selected").val();
            var edit_platform = $("#edit_platform").find("option:selected").val();
            data = {
                "app_id": app_id,
                "app_name_cn": app_name_cn,
                "app_name_en": app_name_en,
                "app_type": app_type,
                "git_url": git_url,
                "git_properties": git_properties,
                "edit_java_version": edit_java_version,
                "edit_platform": edit_platform
            };
            data = JSON.stringify(data);
            var url = "/release/app_edit/";

            $.post(url, {data: data}, function (msg) {
                $('#editInfoModal').modal('hide')
                update_ajax_callback(msg, {{ platformId }});
            });
        });

        /*
*ajax get callback
*/
        function update_ajax_callback(msg, id) {
            var msg = $.parseJSON(msg);
            var index = layer.alert(msg, { //layer控件提示信息
                skin: 'layui-layer-molv' //样式类名
            }, function () {
                if (msg == '成功') {
                    window.location = "/release/platform_app_detail/" + id;
                }
                else if (msg == '失败') {
                    window.location = "/release/platform_app_detail/" + id;
                }
                    {#        else if (msg == '无权限操作'){#}
                    {#            window.location="/cmdb/server_list/";#}
                    {#        }#}
                else {
                    layer.close(index)
                }
            });
        }

    </script>
{% endfor %}